server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/users/**

              filters:
                - TokenRelay
                - StripPrefix=1
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:erp-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9001/realms/master}
            user-name-attribute: sub
